Gal 45 - Creacion de Manage Pack / Edit / Scheduled pack / link to Add Bussiness and Routes
CampusDual/cd2024bfs2g1 pull request #113
Opened 2024-05-30 13:38 UTC by gabriel432-dev

Creamos la pestaña para acceder a manage packs

Creamos la lista para visualizar las plantillas de los packs, que se cargan de forma paginada 

Añadimos navegación mediante un encabezado 

Creamos el formulario para editar una plantilla de pack

Creamos un boton para visualizar una nueva ventana , donde se mostrara el formulario para agendar packs 

Agregamos al formulario de editar una tabla para poder visualizar los packs agendados a esa plantilla

Implementamos la funcionalidad de añadir negocios y rutas, mediante un boton 

Implementamos coherencia en el estilos acorde a los estandares acordados en la spike

añadimos un filtro en el listado de plantillas de packs

Creamos la tabla de packDate, realizamos un cambio en la tabla de pack/packState/PackBoking

agregamos el campo de fecha actual, a packDate, como consecuencia hubo que arreglar el pack home,

2024-05-30 15:12 UTC, cesarsantiagonunez requested changes

2024-05-31 09:43 UTC, 22paaula commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-edit.component.css
> +    background-image: url('../../../../assets/images/fondoPackEditar.png');
Ni siquiera compila 
![image](https://github.com/CampusDual/cd2024bfs2g1/assets/165990968/1ada428f-6dd9-4ca7-a6c3-8680c2d0bd91)

2024-05-31 11:15 UTC, cesarsantiagonunez requested changes

2024-05-31 11:15 UTC, cesarsantiagonunez commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/manage-packages/pack-edit/pack-schedule/pack-schedule.component.ts
> +  @ViewChild("days") days: OIntegerInputComponent
refactorizade, primeiro as variables, despois constructor e metodos da implementacion e o final os vosos metodos

2024-05-31 11:35 UTC, cesarsantiagonunez requested changes

2024-05-31 11:35 UTC, cesarsantiagonunez commented on cd2024bfs2g1-model/src/main/resources/db/migration/V16__create_pack_date_edit_pack_and_state.sql
> +INSERT INTO pack_state(pcs_state)
estos estados xa estan na base de datos, non fan falta estos inserts

2024-05-31 11:35 UTC, cesarsantiagonunez commented on cd2024bfs2g1-model/src/main/resources/db/migration/V16__create_pack_date_edit_pack_and_state.sql
renombrade o script a v15

2024-05-31 11:55 UTC, cesarsantiagonunez approved these changes

2024-05-31 11:56 UTC, merged