GAL-G1-FIX: Acesso denegado a landmarks si no hay
CampusDual/cd2024bfs2g1 pull request #195
Opened 2024-06-14 12:48 UTC by 22paaula

2024-06-14 13:05 UTC, cesarsantiagonunez requested changes

2024-06-14 13:05 UTC, cesarsantiagonunez commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.html
> +                        <li *ngIf="!data.estimated_distance"><i><mat-icon matTooltip="{{'estimated_distance' | oTranslate }}">directions_run</mat-icon></i> - km</li>
por que o cambiades a minuscula?

2024-06-14 13:05 UTC, cesarsantiagonunez commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.html
> +                <li *ngIf="!data.estimated_distance"><mat-icon class="icon">directions_run</mat-icon>- km</li>
e aqui igual

2024-06-14 13:05 UTC, cesarsantiagonunez commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-home/routes-home.component.ts
> +num_landmarks: number;
esta variable non se usa, podedes eliminala

2024-06-17 05:40 UTC, 22paaula commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/routes/routes-detail/routes-detail.component.html
> +                        <li *ngIf="!data.estimated_distance"><i><mat-icon matTooltip="{{'estimated_distance' | oTranslate }}">directions_run</mat-icon></i> - km</li>
Porque cuando si hay datos está en minúscula y era por coherencia

2024-06-17 06:04 UTC, cesarsantiagonunez approved these changes

2024-06-17 06:04 UTC, merged