GAL-G5-AUX
CampusDual/cd2024bfs2g1 pull request #93
Opened 2024-05-27 10:57 UTC by dari0rm

## This branch has all of the necessary changes to make the application functional again after the mayor DB structure overhaul, there are also some minor changes that have been picked out during the process.
### Changes
- [x] Reduced pack new name validator length to 40 to improve pack detail styles
- [x] Removed date begin and end from pack home card
- [x] Removed date begin and end from pack detail 
### Fixes
- [x] Fixed broken pagination query
- [x] Fixed databinding to match new DB structure
- [x] Fixed broken redirect when accessing a pack via URL, this redirect would send the user to my packs causing an error if the user's role did not have the required permissions 
- [x] Fixed packDetailquery, which was returing duplicated data when a pack had more than one entry on the pack_date table

2024-05-27 12:16 UTC, cesarsantiagonunez requested changes

2024-05-27 12:16 UTC, cesarsantiagonunez commented on cd2024bfs2g1-frontend/src/main/ngx/src/assets/i18n/en.json
> +  "VALDOVINO": "VALVODIÑO",
faltan traduccións de idiomas

2024-05-27 12:16 UTC, cesarsantiagonunez commented on cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/pack/PackService.java
> +        if(keysValues.size()>0){
```suggestion
        if(keysValues.containsKey(PackDao.PCK_ID)){
```

2024-05-27 12:16 UTC, cesarsantiagonunez commented on cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/pack/PackService.java
> +            Object key = keysValues.remove("pck_id");
utilizade os placeholders

2024-05-27 12:16 UTC, cesarsantiagonunez commented on cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/pack/PackService.java
> +        attrMap.put(PackDateDao.PD_DATE_END, Utils.iso8601Format.parse((String) dates.get("endDate")));
estas fechas ahora creo que irian contra a taboa pack_date

2024-05-27 12:31 UTC, dari0rm commented on cd2024bfs2g1-model/src/main/java/com/campusdual/cd2024bfs2g1/model/core/service/pack/PackService.java
> +        attrMap.put(PackDateDao.PD_DATE_END, Utils.iso8601Format.parse((String) dates.get("endDate")));
Ya hablamos con el grupo 2 que fue el encargado de ese método y nos dijeron que como habían cambiado el mismo método, que pusheasemos nuestro cambio igualmente y ellos al hacer el merge de su rama con los cambios del método ya dejarían solo lo suyo.

2024-05-27 13:08 UTC, cesarsantiagonunez requested changes

2024-05-27 13:08 UTC, cesarsantiagonunez commented on cd2024bfs2g1-frontend/src/main/ngx/src/app/main/pack/pack-new/pack-new.component.html
> +     keys-sql-types="integer" (onInsert)="insertPacks($event)" confirm-exit="false" class="custom-form">
```suggestion
     keys-sql-types="integer" (onInsert)="insertPacks()" confirm-exit="false" class="custom-form">
```

2024-05-28 06:23 UTC, cesarsantiagonunez approved these changes

2024-05-28 06:23 UTC, merged